karpathy/llm.c

Makefile
I was on a Linux with gcc but no clang installed and when I compiled with gcc I got a bunch of these:
` warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]`
So I thought this might be helpful to silence these warnings, but also to give a little flexibility as to what compiler to use.
After installing clang in Ubuntu, and building with clang, there was no such warnings.
=> Using the compiler at hand

train_gpt2.py
Just fix torch warning of python version.
`train_gpt2.py:333: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:212.)`
=> fix: torch warning of python demo

dev/cuda/matmul_forward.cu
The sqrt_block_size is 32 in `    matmul_forward(kernel_num, d_out, d_inp, d_weight, d_bias, B, T, C, OC, 32);`
thus the printf should have 1024.
=> fix error in small typos in matmul_forward.cu

Makefile, dev/cuda/matmul_forward.cu, test_gpt2.cu, train_gpt2.cu
cc @ademeure , this is cuBLASLt version of matmul only, for now, with a bunch of smaller changes. E.g. I tried to take out global variables and settings, which by default I prefer to do as much as possible. I think the workspace is the only thing that has to stay global (?). (Without streams/graphs involved). I also changed the workspace to 4MiB instead of 64MiB per [official docs recommendations](https://docs.nvidia.com/cuda/cublas/#cublassetworkspace).
When compiling we now add `-lcublasLt`:
```bash
nvcc -O3 --use_fast_math -Xcompiler -fopenmp matmul_forward.cu -o matmul_forward -lcublas -lcublasLt
```
And then these are the timings I am seeing on my A100 40GB PCIe:
```
(pytorch2) ubuntu:~/llm.c/dev/cuda$ ./matmul_forward 2
Using kernel 2
4.452381 4.452382
1.007628 1.007629
0.703605 …
```
=> use cublaslt and optionally tf32, which fuses bias

dev/cuda/softmax_forward.cu
1. Include the online softmax CPU code (from the paper [Online normalizer calculation for softmax](https://arxiv.org/pdf/1805.02867.pdf)).
2. Its native port to GPU kernel `kernel 5` (for education comparison).
3. Include the fully parallel kernel `kernel 6`, where the [reduction op](https://github.com/karpathy/llm.c/pull/79/files#diff-a00ef278da39f24a9d5cb4306c15626b921d437013fb5aa60ac2d8df6b5a5508R362) uses
and cooperative group (from @ngc92 ) .
RTX3070: 
`B=8, T=1024`
Kernal 4:
Kernel 6:
`B=64, T=1024`
Kernal 4:
Kernal 6:
=> Include the online softmax CPU code and a fully parallelized GPU kernal

dev/cuda/attention_forward.cu
Uses a single warp (instead of a block) per token, therefore relying entirely on wrap-level shuffle functionality provided by `cg::reduce`.
Instead of achieving causal attention through masking, since we're looping manually, we may just as well fix the loop bounds to be correct. Finally, do the scaling as part of the computation here, saving us one more round-trip to vram.
I believe this is orthogonal to #79, but I wanted to get the  simple version working first.
=> cooperative groups and fused scale kernel

dev/cuda/attention_forward.cu, dev/cuda/common.h, dev/cuda/crossentropy_forward.cu, dev/cuda/crossentropy_softmax_backward.cu, dev/cuda/gelu_forward.cu, dev/cuda/layernorm_forward.cu, dev/cuda/matmul_forward.cu, dev/cuda/positional_forward.cu, dev/cuda/residual_forward.cu, dev/cuda/softmax_forward.cu
Extracts common parts out of the individual cuda kernel test files.
Makes it easier to write consistent tests (e.g., outputting time per repeat) and also some fixed, e.g., in some places, the old code was not properly free'ing malloced buffers; or claimed to test each block size, but in fact only tested one. 
Some challenges:
* When fusion the scale part into the attention kernel, we get different (unscaled) preatt results than the CPU kernel. Currently, this comparison is commented out. Similarly, checking the attention map doesn't seem to work.
Edit:
The error below was due to the test code not properly resetting the output memory. This is very important for testing backward, since there, we're generally adding instead of overwriting.
* With the new tests, we're testing different block …
=> Extracted common functions for CUDA dev

train_gpt2.cu
This adds the softmax I wrote for #89 optimised for large Cs with very aggressive loop unrolling. Ideally the best ideas of this kernel should be merged with the best ideas of kernel5 (online softmax), but the current kernel5 is likely to be slower because I think it won't have enough parallel warps to keep the entire GPU busy etc...
Also added a few more __ldcs qualifiers for loads with data that won't be read again (or not for a long time), this makes them low priority in the L1/L2 caches and more likely to be replaced by useful data instead.
A100:
Before: 25.1ms
After Softmax: 23.5
After __ldcs: 23.4 (reliably faster, the ~0.1 isn't just noise)
=> New softmax for non-self-attention case optimised for large Cs + add more __ldcs

dev/cuda/crossentropy_forward.cu, dev/cuda/crossentropy_softmax_backward.cu, dev/cuda/gelu_forward.cu, dev/cuda/layernorm_forward.cu, dev/cuda/matmul_forward.cu, dev/cuda/positional_forward.cu, dev/cuda/residual_forward.cu, dev/cuda/softmax_forward.cu
Several changes to the tests:
* Fixes printed timings, some were divided by the repeats twice
* Ensure that every kernel prints a more relative statistic (bandwidth, flops, time per token), and adjust number of digits so we don't spam meaningless decimals
* changed the softmax tests to use  `vocab_dim`  as the number of channels
The last one has several important implications:
First, timings between the kernels might be changed now.
More importantly, the old tests become meaningless, because with uniform logits, we get tiny probabilities for  each  output, and a kernel that just outputs zeros might actually pass the tests.
This can  be fixed  by adding a few "outliers" to the input. With this, even the current kernels fail the tests.
However, this is not because the current kernels are …
=> Test updates

dev/cuda/classifier_fused.cu
This fuses together all the pointwise operations that happen in the token classification layer. This essentially gives us the forward/backward for the cost of about just the forward pass, because this is entirely limited by memory transfers, and we save storing and loading the intermediate probabilities. 
Comes at the cost of losing a bit of flexibility regarding `dlosses`, because now, we already need to know  what we want to backprop. Shouldn't be much of a problem, I think, as long as  we're only considering averages of token-wise losses, with potential predetermined masking.
=> WIP: Fully fused classification layer

dev/cuda/matmul_backward.cu
The original code does pass in Linux.
However, in windows,
```
Device 0: NVIDIA GeForce RTX 3070 Laptop GPU
enable_tf32: 0
Using kernel 1
Checking correctness...
dinp:
12.846249 12.846246
25.214823 25.214817
-13.958217 -13.958220
-15.573501 -15.573508
31.178213 31.178207
dweight:
-40.251938 -40.252014
15.850185 15.850141
-64.966507 -64.966446
-66.537521 -66.537636
-26.666681 -26.666658
dbias:
1.125021 1.125035
26.328951 26.328930
11.523802 11.523788
17.523970 17.523972
16.781780 16.781767
Mismatch of dbias at 158: -305.011322 vs -305.009247
```
Modify the CPU code to reach logic parity (using double `sum` as the accumulator for float) with the GPU code and results match after the fix.
=> Fix the backward dbias precision issue in matmul_backward

train_gpt2.cu
@karpathy I have two solutions to fix the out-of-resource issue that some folks are observing (see https://github.com/karpathy/llm.c/issues/106). We are hitting this issue due to excessive register usage and the compiler is unable to determine it well. The two solutions to this are: 
a) keep the block_size = 1024 and add __launch_bounds__(1024, 2) as a prefix as shown below. This would force register spills to the memory subsystem. 
```
__global__ void layernorm_forward_kernel3(float* __restrict__ out, float* __restrict__ mean, float* __restrict__ rstd,
const float* __restrict__ inp, const float* __restrict__ weight,
const float* __restrict__ bias, int N, int C) {
```
to below 
```
__global__ __launch_bounds__(1024,2)
void layernorm_forward_kernel3(float* __restrict__ out, float* …
```
=> simple fix for bug [#106]

Makefile, README.md
final compilation opts on cpu, -fno-finite-math-only instead of -fno-fast-math, and add -march=native.
benchmarks comparisons: https://github.com/karpathy/llm.c/issues/19#issuecomment-2049099144
and now:
```bash
step 0: train loss 5.356086 (took 9611.016869 ms)
step 1: train loss 4.300644 (took 8780.770364 ms)
step 2: train loss 4.623083 (took 7137.313333 ms)
step 3: train loss 4.599365 (took 6426.557283 ms)
step 4: train loss 4.616659 (took 6864.495874 ms)
step 5: train loss 4.231428 (took 6635.326672 ms)
step 6: train loss 3.753164 (took 6516.244371 ms)
step 7: train loss 3.650456 (took 6362.145571 ms)
step 8: train loss 4.182243 (took 6333.873539 ms)
step 9: train loss 4.199581 (took 6407.929416 ms)
```
=> -fno-finite-math-only for almost 2x speed up, fix for [#19]

dev/cuda/adamw.cu
I've implemented a naive CUDA kernel for the AdamW optimizer. I have also added a slightly faster version, but it's probably possible to optimize it further.
Outputs using 1M random parameters:
```
$ ./adamw 1
Device 0: GeForce RTX 2080 Ti
Using kernel 1
Checking correctness...
parameters:
0.680332 0.680332
-0.211399 -0.211399
0.566104 0.566104
0.596687 0.596687
0.823023 0.823023
first moment:
0.243864 0.243864
0.590244 0.590244
0.470778 0.470778
0.301208 0.301208
0.766460 0.766460
second moment:
0.754159 0.754159
0.299961 0.299961
0.586026 0.586026
0.057003 0.057003
0.186383 0.186383
All results match.
time gpu 0.0563 ms
time cpu 0.1800 ms
```
Outputs using the faster kernel:
```
$ ./adamw 2
Device 0: GeForce RTX 2080 Ti
Using kernel 2
Checking correctness...
parameters:
0.680332 …
```
=> AdamW CUDA kernel

dev/cuda/attention_backward.cu, train_gpt2.cu
Uses one warp (instead of one thread) for each  result that is to be computed. We gain coalesced access in the inner loop, translating to a tremendous speedup.
=> coleased memory reads for faster backward pass in attention

dev/cuda/attention_forward.cu
Fix the number of elements to check when verifying attention implementations.
This was causing me problems when I was trying to debug a new implementation on fewer tokens.
=> fix(attention_forward.cu): Fix the number of elements to check

dev/cuda/classifier_fused.cu
This is a faster version of the cool new kernel from #117 (still /dev/cuda/ only). The biggest difference is it is optimised for doing one row per 1024-wide block rather than per 32-wide warp, which massively reduces the amount of data in-flight, and this allows us to basically always hit in the L2 cache for the 2nd read and this saves a huge amount of DRAM bandwidth. It also uses 128-bit loads which implicitly requires V to be a multiple of 4.
However, I believe the validation in classifier_fused.cu is currently not working correctly, possibly because the distribution of inputs results in all probabilities being ~zero, which is something I think ngc92 has a fix for.
Finally, I changed both old and new kernels to write to the gradient tensor, rather than modify it (read-modify-write) …
=> Optimised version of fused classifier + bugfixes(?)

dev/cuda/attention_backward.cu, train_gpt2.cu
Backward kernel where threads reuse data in registers to reduce memory transfers.
This PR is build on top of my previous PRs, which should be merged first. Once that is done, I'll rebase and remove the draft status here. But I need the changes to backward pass memory allocation, otherwise I cannot profile the backward pass because I get  OOMs; and also, I need to be able to assume that the kernel writes (=) instead of accumulate (+=) its gradients.
=> Further improvements to attention backward

dev/cuda/attention_backward.cu, dev/cuda/common.h, train_gpt2.cu
Back to the drawing board, because I think the other kernels hit a local minimum, or at least the way the loops where organized made it very difficult to think about how to optimize this further.
I think there is quite a bit of room to optimize this version further, but for educational purposes, I think it is better to have a simpler version first, where the main idea is evident, and then go crazy with the optimizations in a second version.
This design limits T to multiples of the block_size. Incidentally, on my system at least, block size 64 turns out to be fastest, which actually is compatible with both our training at test scripts.
=> towards an even better backward attention kernel

dev/cuda/attention_backward.cu, train_gpt2.cu
Both noticeably faster and quite a bit simpler, since we no longer need all these `t3 <= t`  checks :)
Also removed the ` __launch_bounds__`, produced bad results for 256 block size. We  can tune that once this kernel stabilizes.
=> separating the loops leads to yet more improvements

README.md
This pull request adds a link to a Mojo port of this project under the "Notable Forks" section of the README.
=> Added link to Mojo port in Notable Forks section

Makefile, profile_gpt2.cu
makes sure we see each kernel show up in the profile, while being as fast as possible (i.e, running only for one layer, for one step)
also gets compiled with lineinfo by default
=> profiling script

Makefile, train_gpt2.c
Please see https://github.com/karpathy/llm.c/pull/168 for details and work being done on optimizing the activation function on CPU.
This PR results in a 10-23% speedup on CPU and has been tested on `msvc` and `gcc` on x86 and fixes #19
=> Fixes -Ofast optimizations breaking model by skipping them for gelu_backward

test_gpt2.cu, train_gpt2.cu
With the fused classifier layer, there is actually no need to track logits and dlogits separately, and we can reuse that buffer.
Requires slight changes to the testing script, so we don't test dlogits.
Further, the helper buffers in the attention code aren't actually used during backward, so we really don't need on copy per layer.
=> Further memory reductions

.gitignore, Makefile
I tried to build on my mac and ran into a build error
```
$ make
NICE Compiling with OpenMP support
cc -Ofast -fno-finite-math-only -Wno-unused-result -march=native -Xclang -fopenmp -DOMP  -I/opt/homebrew/opt/libomp/include  -L/opt/homebrew/opt/libomp/lib train_gpt2.c -lm -lomp -o train_gpt2
clang: error: the clang compiler does not support '-march=native'
make: *** [train_gpt2] Error 1
```
It seems like the flag -march=native was not supported on my clang compiler.
I introduced the CFLAGS_COND as a list of CFlags that are included only if the CC supports it.
I also only build the nvcc targets if nvcc is installed.
=> Support for vanilla build without CUDA tools

test_gpt2.cu, train_gpt2.cu, train_gpt2.py
Currently fails the test, because right now there is no way to get logits out of the model
Run as training => get  dlogits
Run for inference => get probs
The memory savings are quite substantial, though:
```
allocated 7127 MiB for activations
allocated 1421 MiB for activation gradients
=>
allocated 5946 MiB for activations
allocated 636 MiB for activation gradients
```
=> Yet more memory reductions

dev/cuda/matmul_forward.cu
bt  is always less than BT. so no need to get b = bt / BT and t = bt % BT.
=> fix indexing in matmul_forward_kernel1

dev/cuda/common.h, dev/cuda/trimat.cu
Companion to #213, adding a file specifically for the development of this matmul.
Also shows different intermediate kernels on the way towards efficiency. 
To give a break from all the maths and indexing in the code, the development of these is described as a story. 
Some of the metaphors are stretched quite a bit, so feel free to make adjustments, but I  hope that overall, this might be easier to follow than just "indexing with this formula to achieve coalesced access".
Currently, the reads in the inner loop still cause 2-way bank conflicts, so there is still room for improvement.
Timings on my machine:
>  time 1.40 ms vs 2.37 ms for CuBLAS
Given that we're doing only half the work, that leaves us still 20% less efficient than cuBLAS.
=> added triangular matrix multiplication kernel

README.md
This is a fork of llm.c, designed to take full advantage of Apple Silicon via the Metal framework. Just got the forward pass working and will start on the backward pass. I wrote a minimal C wrapper API over the Objective-C Metal API that was needed to set up and run compute shaders. The rest of the code is pure-C and Metal Shading Language. I'm trying to mirror the original repo as closely as possible both in code and project philosophy.
=> Added llm.metal to notable forks

dev/cuda/matmul_backward_bias.cu, train_gpt2.cu
This kernel seems to offer a <4x runtime improvement over `matmul_backward_bias_kernel2` on an RTX 2070 Super GPU, runtime comparison shown below:
```
matmul_backward_bias_kernel2:
block_size 32 time 0.9027 ms
block_size 64 time 4.0396 ms
block_size 128 time 3.4077 ms
block_size 256 time 1.4159 ms
block_size 512 time 0.7302 ms
block_size 1024 time 0.9947 ms
matmul_backward_bias_kernel4:
block_size 32 time 0.6875 ms
block_size 64 time 0.4235 ms
block_size 128 time 0.2925 ms
block_size 256 time 0.2419 ms
block_size 512 time 0.2714 ms
block_size 1024 time 0.2519 ms
```
The kernel passes `test_gpt2cu` without any issue, and also the tests in `dev/cuda/matmul_backward_bias.cu` *after increasing the tolerance from 1e-3 to 5e-3*: with the tolerence set to 1e-3, the weights printed to the console …
=> Faster `matmul_backward_bias` using coalesced reads and shared memory in the kernel

dev/cuda/layernorm_backward.cu, train_gpt2.cu
This cr was made to address the issue found in the profiler that the atomic operations in the final loop of this kernel were causing a bunch of warp stalls. By doing the atomic operation on shared memory instead of global memory and then copying the shared memory afterwards it signifigantly reduces the time by almost a factor of 4 for the largest block sizes:
Before:
```
block_size   32 time 0.3854 ms
block_size   64 time 0.4663 ms
block_size  128 time 0.4643 ms
block_size  256 time 0.4715 ms
block_size  512 time 0.4740 ms
block_size 1024 time 0.4769 ms
```
After:
```
block_size   32 time 0.3658 ms
block_size   64 time 0.2301 ms
block_size  128 time 0.1782 ms
block_size  256 time 0.1526 ms
block_size  512 time 0.1426 ms
block_size 1024 time 0.1431 ms
```
=> Added shared memory for the atomic additions for the layernorm_back

train_gpt2.c
Keeping it simple. `msvc` compiles again and `clang` doesn't issue warnings.
=> Make msvc compile by adding the ifdefs back in gelu_backward, fixes #200

test_gpt2.cu, train_gpt2.cu
Now finished and reasonably happy with it!
1.86x performance on my RTX 4090:
- FP32: ~80ms
- BF16: ~43ms (with layernorm params in FP32, but all activations in BF16)
This allows the same train_gpt2.cu to work as full FP32, full BF16, full FP16, or full (BF/FP)16 + FP32 layernorm simply by changing the define at the top of the file. Also included stochastic rounding for the Adam kernel (but nothing else at this point, possibly worth adding to gradients in general when we move to FP8?)
To simplify the logic compared to the first version of the PR, all activation tensors are now always "floatX", we cannot mix-and-match. However, because atomicAdd on 16-bit values in some of the backwards kernels are HORRIBLY slow (10x slower or worse), and because this kind of flexibility seems useful in …
=> Support for FP16/BF16 in train_gpt2.cu (1.86x Perf)

train_gpt2.cu
* To increase compatibility, if FP16/BF16 isn't actually enabled, we can disable the definition of atomics that cause compile failures for older GPUs
* calculation for `num_activations` was wrong
=> Small fixes

.gitignore, dev/cuda/Makefile, dev/cuda/README.md, dev/cuda/encoder_backward.cu, dev/cuda/layernorm_backward.cu
Adds a local convenience Makefile for dev/cuda/ with individual targets, `all`, `run`, and `clean`. The compiler invocations largely follow the header comments for each target. One minor exception is `matmul_backward_bias.cu` (removed the `-lineinfo` flag in the Makefile).
While building the `all` target, there were two minor warnings for `encoder_backward.cu` and `layernorm_backward.cu` which are also patched here.
=> Add a local convenience Makefile for dev/cuda/

Makefile, profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu, train_gpt2.py, train_gpt2_fp32.cu
Code to load bf16 weights directly, and also re-wire the position of tensors to put the layernorms (which are in fp32) at the end. the training loop seems to work ok, and the tests pass and the loss and optimization looks ok, but the gradients don't match. which can't be right. so there is a bug, but it's a bit too late in the day for me to debug right now, creating a PR and going to sleep, will fix tomorrow
=> load bf16 directly, and some "quality of life" handling of fp32/fp16/bf16 precisions

dev/cuda/encoder_forward.cu
On RTX 3070
Kernel 2
```
block_size   32 | time 0.2933 ms | bandwidth 343.26 GB/s
block_size   64 | time 0.2099 ms | bandwidth 479.50 GB/s
block_size  128 | time 0.1924 ms | bandwidth 523.24 GB/s
block_size  256 | time 0.1979 ms | bandwidth 508.77 GB/s
block_size  512 | time 0.1947 ms | bandwidth 516.96 GB/s
block_size 1024 | time 0.2276 ms | bandwidth 442.33 GB/s
```
Kernel 3 runtime is more stable across different blocksize and is faster in terms of the best execution time.
```
block_size   32 | time 0.1902 ms | bandwidth 529.21 GB/s
block_size   64 | time 0.1908 ms | bandwidth 527.52 GB/s
block_size  128 | time 0.1919 ms | bandwidth 524.55 GB/s
block_size  256 | time 0.1916 ms | bandwidth 525.45 GB/s
block_size  512 | time 0.1923 ms | bandwidth 523.43 GB/s
block_size 1024 | time 0.1896 …
```
=> float4 with better vectorization for encoder_forward.cu

Makefile
Tested locally and reduced compilation time by 200ms, unfortunately for me upgrading to 12.4 made my compilations times slow by 2x but at least this can make it a bit faster
=> Enable multithreading in nvcc

README.md
Zig port link is incorrect and pointing to wrong page
* Fixed Zig port link
* Fixed link to the zig port's author
=> Fix link to zig port in README.md

dev/cuda/common.h, dev/cuda/layernorm_backward.cu, test_gpt2.cu, train_gpt2.cu, train_gpt2.py
I added 4 different new versions of layernorm_backward_kernel, performance is best for:
- Kernel 4 (using atomicCAS, no scratch, but rounding many times so probably worse numerical accuracy
- Kernel 6 ==> new default (FP32 scratchpad, do one final rounding to BF16 at the end, could be made stochastic in the future).
We probably just want to integrate Kernel 6 but might want to add all of them to /dev/cuda/ in the future. I haven't fixed the BF16 atomics in encoder_backward yet but the performance penalty of that is much much smaller, it might be worth doing it manually using atomicCAS so we can implement stochastic rounding there as well though.
Performance on my RTX 4090 is a tiny bit faster (potentially noise) than with the previous mixed FP32/BF16.
=> Full BF16 including layernorms by default (minimising number of BF16 atomics)

train_gpt2.cu
The MULTI_GPU path is untested, but everything else seems to work fine. I kept the per-tensor "param_sizeof" as it's used in test_gpt2.cu for example, it's not much code and may be useful again in the future.
This will create merge conflicts with #289 but hopefully not hard to fix.
=> Remove FloatN & simplify adam/reduce with BF16 LayerNorms

train_gpt2.cu
At the beginning when defining the constants per data type, there are some shared values across all data types that are repeated. This PR seperates the out more clearly and reduces the duplication.
=> Changed ordering of type configuration to easily see unchanged values

dev/cuda/common.h
we've recently been bitten by this, so here is an attempt to make our measurements more reliable
=> clear the L2 cache between benchmarks

dev/cuda/README.md, dev/cuda/benchmark_on_modal.py
This PR adds a script to run the benchmarks on the [Modal platform](https://modal.com). This is useful for folks who do not have access to expensive GPUs locally.
To run the benchmark for the attention forward pass on an A100 GPU with 80GB of memory, you can run the following command:
```bash
GPU_MEM=80 modal run benchmark_on_modal.py --compile-command "nvcc -O3 --use_fast_math attention_forward.cu -o attention_forward -lcublas" --run-command "./attention_forward 1"
```
=> Add script to run benchmarks on Modal

dev/cuda/gelu_forward.cu, train_gpt2.cu
This PR implements packing for the Gelu forwards kernel using the example provided. The kernel dev file was also updated to show the impact of changing the data types for floatX.
Before changes:
total average iteration time: 38.480425 ms
After changes:
total average iteration time: 37.817789 ms
Before:
block_size   32 | time 0.1502 ms | bandwidth 335.17 GB/s
block_size   64 | time 0.0761 ms | bandwidth 661.65 GB/s
block_size  128 | time 0.0404 ms | bandwidth 1246.72 GB/s
block_size  256 | time 0.0376 ms | bandwidth 1337.40 GB/s
block_size  512 | time 0.0389 ms | bandwidth 1294.26 GB/s
block_size 1024 | time 0.0407 ms | bandwidth 1235.78 GB/s
After:
block_size   32 | time 0.0225 ms | bandwidth 2232.26 GB/s
block_size   64 | time 0.0198 ms | bandwidth 2547.13 GB/s
block_size  128 | time …
=> Added packing for gelu forwards kernel

dev/cuda/common.h, dev/cuda/gelu_forward.cu
This adds a helper function for safe casting from size_t to ints (may want to have that in utils.h too).
that macro is then used to convert the size_t valued  `block_size * x128::size` back to a regular int.
also, there is no need to restrict our kernels to just one specific dtype. Let's just compile them for all dtypes, so we can compare. The only thing we need to adjust is the test tolerance.
=> fixed potential error and generalized gelu forward

Makefile, dev/cuda/attention_forward.cu, profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
RTX 4090 with BF16 and batch size of 24:
- Baseline: 232.37ms (~106K tokens/s)
- cuDNN: 170.77ms (~144K tokens/s) ==> **+35% performance!**
- Compile time: Priceless(TM) (~2.7s to 48.7s - it's a big dependency and part of the reason PyTorch is so big!)
In the future we'd ideally want to implement our own version of this and hopefully avoid the requirement to include cuDNN for maximum performance, but for now it allows the GPU to go brrrrrrrrrrrrrrrrr! :)
Currently on by default with #define ENABLE_CUDNN at the top of train_gpt2.cu, this should probably become a Makefile change and become off by default. Potentially using cudnn-backend directly instead of cudnn-frontend would result in lower compile times, but that would be a lot of work and frontend is what NVIDIA recommends these days. …
=> cuDNN Flash Attention Forward & Backwards BF16 (+35% performance)

train_gpt2.cu
uint isn't defined by the MS compiler and designated initializers aren't part of the C++ standard until C++ 20. A couple of small changes to allow them to compile with MS C++ compiler.
=> uint and designated initializers non-standard for C++ / Cuda

dev/cuda/classifier_fused.cu, train_gpt2.cu
Using the guide from https://github.com/karpathy/llm.c/issues/292 removed the cooperative groups and then implemented packed128 in both of those functions.
Before:
total average iteration time: 38.403503 ms
After:
total average iteration time: 38.053227 ms
=> Removed cooperative groups and added packed128 to fused classifier and prepare softmax blockwide

requirements.txt
When run `quick start (GPU)`
```bash
pip install -r requirements.txt
python prepro_tinyshakespeare.py
python train_gpt2.py
make train_gpt2fp32cu
./train_gpt2fp32cu
```
It has the ModuleNotFoundError `No module named requests`, thus, I edit `requirements.txt` to solve this issue.
Original `requirements.txt`L
```bash
tqdm
numpy
torch
tiktoken
transformers
```
Fixed `requirements.txt`:
```bash
tqdm
numpy
torch
tiktoken
transformers
requests
```
=> [ModuleNotFoundError]: Solution - add required package (requests) into requirements.txt

dev/cuda/layernorm_backward.cu, train_gpt2.cu
Following the instructions in https://github.com/karpathy/llm.c/issues/292 I removed the cooperative groups from this kernel using warp sums. Did not have a detectable impact on performance for me.
=> Added example of removing cooperative groups in layernorm backwards

dev/cuda/Makefile, dev/cuda/gelu_backward.cu, train_gpt2.cu
Update gelu backwards kernel to do packing into 128 bits, and create gelu brackward cuda file
Previous kernel:
block_size   32 | time 0.1498 ms | bandwidth 503.99 GB/s
block_size   64 | time 0.0760 ms | bandwidth 993.32 GB/s
block_size  128 | time 0.0490 ms | bandwidth 1540.78 GB/s
block_size  256 | time 0.0487 ms | bandwidth 1548.88 GB/s
block_size  512 | time 0.0487 ms | bandwidth 1548.88 GB/s
block_size 1024 | time 0.0497 ms | bandwidth 1518.38 GB/s
total average iteration time: 39.030942 ms
New Kernel
block_size   32 | time 0.0328 ms | bandwidth 1535.18 GB/s
block_size   64 | time 0.0319 ms | bandwidth 1575.59 GB/s
block_size  128 | time 0.0333 ms | bandwidth 1509.35 GB/s
block_size  256 | time 0.0337 ms | bandwidth 1491.94 GB/s
block_size  512 | time 0.0340 ms | bandwidth 1478.92 …
=> Packing for Gelu backwards

dev/cuda/residual_forward.cu, train_gpt2.cu
Update residual_forward to use 128 bit packed input, with floatX
Previous Kernel:
block_size   32 | time 0.1498 ms | bandwidth 503.99 GB/s
block_size   64 | time 0.0760 ms | bandwidth 993.32 GB/s
block_size  128 | time 0.0490 ms | bandwidth 1540.78 GB/s
block_size  256 | time 0.0487 ms | bandwidth 1548.88 GB/s
block_size  512 | time 0.0487 ms | bandwidth 1548.88 GB/s
block_size 1024 | time 0.0497 ms | bandwidth 1518.38 GB/s
total average iteration time: 39.030942 ms
New Kernel
block_size   32 | time 0.0219 ms | bandwidth 3440.86 GB/s
block_size   64 | time 0.0214 ms | bandwidth 3522.09 GB/s
block_size  128 | time 0.0223 ms | bandwidth 3392.29 GB/s
block_size  256 | time 0.0225 ms | bandwidth 3357.22 GB/s
block_size  512 | time 0.0226 ms | bandwidth 3333.70 GB/s
block_size 1024 | time …
=> Update residual_forward to use packed input

train_gpt2.cu
- CUDA events allow for more accurate timings (as measured by a GPU)
- `nvtxRangePush`/`nvtxRangePop` Adds simple stack traces to NSight Systems:
- Sample run command: `nsys profile mpirun --allow-run-as-root -np 2 ./train_gpt2cu`
- Then inspect the resulting profile on a local machine with NVidia NSight Systems.
You'll see something like this in NSight for GPU profile:
=> Add NSight Compute ranges, use CUDA events for timings

profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
I might need to split this into multiple PRs, let me know what you think (and I still need to add the new kernels to /dev/cuda/).
Major changes:
1. New super optimised matmul_backward_bias_kernel6
2. CUDA streams to parallelise a lot more things - ironically, the one big thing missing to prevent all remaining CPU-GPU synchromnisation is the "cudaEventSynchronize(end)" used for getting the performance...
3. Fix for cache hint in fused_classifier (significant perf gain, ~7 to ~5ms on my GPU)
4. Remove cooperative groups from remaining kernels + new blockReduce() helper
=> Performance: matmul_bias, cuda streams, fused_classifier (+remove cooperative groups)

Makefile
Using the same code from the latest kernel Makefile changes from https://github.com/karpathy/llm.c/pull/341,  this auto-detects the GPU or lets you override the GPU capabilities. This PR is small and independent of the upcoming cuDNN Makefile changes.
Usage:
Auto detect GPU capability:
make
(e.g. if your GPU capability type is 80 then --generate-code=arch=compute_80,code=[compute_80,sm_80] is used with CFLAGS)
Do not specify capability:
make GPU_COMPUTE_CAPABILITY=
(CFLAGS = -O3 --use_fast_math)
Override capability:
make GPU_COMPUTE_CAPABILITY=86
(e.g. even if your GPU capability type is 80 then --generate-code=arch=compute_86,code=[compute_86,sm_86] is used with CFLAGS)
Tested on Windows 11 and Linux Ubuntu 22.04. Has the extra space fix (uses strip()) from the kernel Makefile.
=> main Makefile auto-detect GPU capability and allow overrides

train_gpt2.py
This improves perf somewhat, since currently it's always returning logits (which thus need to be materialized).
=> Don't return logits during training for PyTorch baseline

train_gpt2.cu
- put unistd.h back for windows compilation - needs this to find M_PI
- #undef FLT_MAX - used to fix collision with redefinition below ~line 686
- fixed () with preprocessor conditional and removed nonstandard use of "not" and "and".
- uint -> unsigned int
Microsoft compilation is stricter than GCC at times. Tested on Win 11 and Ubuntu 22.04.
=> Replace non-standard C syntax with standard C syntax - fix win compilation

dev/cuda/classifier_fused.cu, dev/cuda/common.h, dev/cuda/layernorm_backward.cu, train_gpt2.cu
These are fairly difficult optimisations to describe, hopefully the comments are helpful/enough! I'd focus on the changes in train_gpt2.cu rather than the similar ones in /dev/cuda/ (I didn't include a dev version of the new bias kernel, that file is very out of date and needs other changes).
layernorm_backward needed x128 but with the additional complexity that atomics are normally 32-bit rather than 128-bit, so naively implementing this resulted in an 8-way bank conflict and terrible performance! It required doing everything in a bank friendly order then reordering before the final write to global memory. This is kind of an annoying side-effect of x128, I think on Hopper there is a native 128-bit atomicAdd though.
matmul_backward_bias is roughly the same story except that was already …
=> Optimisations for layernorm_backward / matmul_backward_bias / fused_classifier

Makefile, README.md, dev/cuda/attention_forward.cu
- Modifies `README.md` to provide example apt-get cuDNN install instructions that install the cuDNN dev package. `sudo apt-get install -y cudnn` will install the default cuDNN packages, but for a minimal setup, installing the dev package will see a 50% reduction in both, download size (~850MB to 425MB now) and local storage size (~2GB to ~1GB now).
- Modifies the `Makefile` to point users to the README for cuDNN install instructions (through comments and the cuDNN install error message)
- Modifies `attention_forward.cu` comments to point users to the README for cuDNN install instructions
=> Adds cuDNN install instructions for a smaller but sufficient package

Makefile, README.md
On Linux, `cudnn-frontend/include` was not detected when installed in the repo directory. This patch fixes this, with some gardening of the howto instructions for cudnn-frontend.
=> Fix detection of cudnn-frontend in '.' on Linux

dev/cuda/adamw.cu, dev/cuda/attention_backward.cu, dev/cuda/attention_forward.cu, dev/cuda/crossentropy_forward.cu, dev/cuda/crossentropy_softmax_backward.cu, dev/cuda/encoder_backward.cu, dev/cuda/encoder_forward.cu, dev/cuda/fused_residual_forward.cu, dev/cuda/gelu_backward.cu, dev/cuda/gelu_forward.cu, dev/cuda/layernorm_backward.cu, dev/cuda/layernorm_forward.cu, dev/cuda/matmul_backward.cu, dev/cuda/matmul_backward_bias.cu, dev/cuda/nccl_all_reduce.cu, dev/cuda/residual_forward.cu, dev/cuda/softmax_forward.cu, dev/cuda/trimat_forward.cu
Due to the `void setup_main()` in the common.h,
```
// setup cuBLAS and cuBLASLt
cublasCheck(cublasCreate(&cublas_handle));
cublasCheck(cublasLtCreate(&cublaslt_handle));
cudaCheck(cudaMalloc(&cublaslt_workspace, cublaslt_workspace_size));
```
added ` -lcublas -lcublasLt` in the comment for compile for consistency.
Or, we can simply remove the comment for compile since everything is in the makefile already.
=> Update the -lcublas -lcublasLt flag in the comment

dev/cuda/matmul_backward_bias.cu, train_gpt2.cu
* fixed up `dev/cuda/matmul_backward_bias.cu` to support bf16.
* added kernel7 to dev/cude
* new  kernel 8 that reduces the number of channels handled by each block by a  factor of 4.  => reduction of global atomics
* Within-block reductions are handled deterministically  using warp shuffles. 
* For large enough OC, we can actually switch off the intermediate buffer and write the result directly. For the A4000, the OC dimension in the hidden layers would be large enough to disable the intermediate buffer for the 120M model with 1024 block size.
* On the A4000, I observe about 4% speed-up for this kernel.
While this change doesn't yet provide full determinism for bias gradient, it already drastically reduces the number of atomics. In a follow-up, we probably should just use a buffer of …
=> Backward bias

dev/cuda/common.h, dev/cuda/layernorm_backward.cu, train_gpt2.cu
This fixes gradient accumulation  for the layernorm backward pass, and provides general modernization of the layernorm backward dev/cuda  file.
Tolerances have been adapted to the float scratchpad kernel, so we now have meaningful correctness test.
All correctness tests have an additional relative tolarance based on the machine epsilon of fp32/bf16. 
Make sure validate exits if there are any errors, not just if there are more than 10.
=> Layernorm backward updates

train_gpt2.c
Removing the hardcoded GPT2_EOT and using the one from the tokenizer instead
=> train_gpt.c: Removing the hardcoded GPT2_EOT

profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
First, clean up the multi-gpu code a bit. We only need to `#ifdef` away sections that would lead to compile errors, anything else can be handled with a regular plain if, making the code more readable. Also gets rid of the two copies of the update function, let's keep the unified as long as we can.
the current ZERO-1 implementation performs an all-reduce on the gradients, but only one shard is actually needed per rank.
As per the zero paper, 
> State-of-art implementation of all-reduce uses a two-step approach, where the first step is a reduce-scatter operation, which reduces different part of the data on different process. The next step is an all-gather operation where each process gathers the reduced data on all the process. The result of these two steps is an all-reduce.
The claim that …
=> Zero update

dev/cuda/matmul_backward_bias.cu, train_gpt2.cu
If we have too many blocks for deterministic within-block reduction, use a larger scratch buffer to do a deterministic reduction in a second kernel call.
=> Deterministic backward bias

dev/cuda/softmax_forward.cu
Following the instructions in #292, I implement [online softmax forward](http://arxiv.org/abs/1805.02867) kernel that without cooperative groups (`softmax_forward_online_kernel2()` used).
About the performance, this implementation is close to `softmax_forward_online2()` and faster than `softmax_forward_online1()` (online softmax without optimizations)
and 
`softmax_forward7()` (normal softmax with optimizations). 
My GPU: 3070 Laptop
My OS: Ubuntu 22.04
`softmax_forward_online8()` (This implementation)
```
block_size   32 | time 14.1648 ms | per token 1.73 µs
block_size   64 | time 13.0965 ms | per token 1.60 µs
block_size  128 | time 12.7798 ms | per token 1.56 µs
block_size  256 | time 13.1108 ms | per token 1.60 µs
block_size  512 | time 14.8191 ms | per token 1.81 µs
block_size 1024 | …
```
=> Free cooperative groups implementation of online softmax forward

train_gpt2.cu
small changes to how we handle gpu memory:
* allocate just once for the adam state
* print before allocation => makes it easier to see how things go wrong in OOM situations
* fixed memleak/duplicate allocation of cublaslt_workspace
=> slight memory management improvements

dev/cuda/Makefile, dev/cuda/global_norm.cu, profile_gpt2.cu, profile_gpt2cu.py, test_gpt2.cu, train_gpt2.cu, train_gpt2.py
one new kernel that calculates the overall norm of the gradient, and updates to the adam kernel.
Still TODO:
* clip value is hardcoded at function call site
* error handling for broken gradients would fit nicely into this change, but it currently only very rudimentary
* there is a debug print statement there. This debug print is in the kernel because  we never move gradient norms to the host, but really, it should be removed once the code is ready for merge.
* ~python reference needs to be updated~
=> gradient clipping by global norm

train_gpt2.cu
When investigating the properties of the WarpSize cuda constant, it is not available at compile time meaning that the compiler is unable to make compile time optimizations based on the value of the WarpSize.
=> Added warpsize as a constant for better compile time optimization and standardization

train_gpt2.cu
From the profiler it appears that around 3% of all of the warp stalls are coming from the bounds checks, we should be able to perform the validations outside of the kernels through asserts instead of checking the boundaries in the kernels
=> Moved bounds checks to outside of the kernel

rand.h
Adding numerically identical to torch rand utils for when we need to init_from_scratch https://github.com/karpathy/llm.c/issues/243
We can init on a CPU and mem copy to GPU.
Usage:
```c
mt19937_state state;
manual_seed(&state, 137);
printf("%u\n", randint32(&state));
printf("%u\n", randint32(&state));
printf("%u\n", randint32(&state));
printf("%u\n", randint32(&state));
printf("%u\n", randint32(&state));
float t8[8];
normal_(t8, 8, 0, 1, &state);
for (int i = 0; i < 8; i++) {
printf("%f\n", t8[i]);
}
printf("%u\n", randint32(&state));
float t16[16];
normal_(t16, 16, 0, 1, &state);
for (int i = 0; i < 16; i++) {
printf("%f\n", t16[i]);
}
printf("%u\n", randint32(&state));
```
```python
import torch
torch.manual_seed(137)
print(torch.randint(0, 0xFFFFFFFF, [1]).item()) …
```
=> Adding Mersenne Twisters Impl.

dev/data/data_common.py, dev/data/fineweb.py
maybe we should extract tokenization+sharding into a `data_common` utility function?
in any case, for fineweb, this results in a noticable overall speedup (almost 2x tok/s on my old threadripper), and drastically reduced memory consumption, because we immediately compress tokens to 16 bit, instead of accumulating in 64 bit and compressing in the end
=> update fine-web preprocessing: faster, and much less RAM consumption

dev/cuda/layernorm_backward.cu, train_gpt2.cu
This causes a small ~0.3% performance loss on my RTX 4090, possibly worse on a A100 since that kernel might be a slightly larger % of total runtime.
It does the 2nd part of the reduction in a single block at the end of the same kernel, so it is extremely occupancy/latency limited, it might be possible to split the 2nd part of the kernel into a separate kernel and optimise it completely differently for better performance. But this feels good enough for now...
This also fixes a bug due to a missing CEIL_DIV that means the XL model with 1600 hidden dimension would not have worked correctly.
After this and encoder_backward, the only missing piece to get rid of all atomics (=> hopefully fully deterministic) is changing global_norm_squared_kernel to do the final reduction on the CPU.
=> Fully deterministic layernorm backward

profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
This is a complete rewrite of the encoder backward pass, splitting it into two kernels (wte and wpe) which are both fully deterministic as they do not use atomics (assuming the seed for stochastic rounding is also deterministic, ofc).
The performance of the wte kernel and the associated CPU overhead are quite input-dependent, it might be quite slow for pathological cases (e.g. all tokens are the same). I tried updating /dev/cuda/ and there were a few problems. Most importantly, the performance on the random inputs was bad on the CPU side, and there was no way to hide the significant CPU overhead unlike in the real training loop.
Interestingly, profile_gpt2.cu is also broken when profiling the *current* encoder_backward: it is unrealistically fast (or more likely the train_gpt2.cu one is …
=> Fully deterministic encoder backward kernels

train_gpt2.c
Not sure how much we care about perf of the CPU version. This is trying to give a substantial boost, while still keeping complexity in check: without the comments, the  matmul still fits on a single screen.
While it would have been possible to either just print an error message for "bad" shapes, or write a function that is more generic and handles the unrollable part followed by an epilogue loop, I think the approach of having a slow, but very simple version, and a fast, but shape-restricted version is better. It keeps the fast algorithm more readable, and having the slow version there as a reference has pedagogical value in itself.
I have also removed the helper row pointers (`out_bt`), because they make it more difficult to see the strides of the individual memory accesses.
On my …
=> considerably speed up CPU matmul

dev/cuda/matmul_backward_bias.cu
Due to the reduction in line https://github.com/karpathy/llm.c/blob/master/dev/cuda/matmul_backward_bias.cu#L67 
The block size needs to be the power of 2 for the `kernel 1`. Otherwise the GPU result is wrong:
```
Using kernel 1
Checking correctness...
1.125032 1.054688
26.328930 26.375000
11.523789 11.437500
17.523972 17.500000
16.781761 16.750000
All results match for block_size=32.
Checking correctness...
1.125032 1.054688
26.328930 26.375000
11.523789 11.437500
17.523972 17.500000
16.781761 16.750000
All results match for block_size=64.
Checking correctness...
1.125032 1.054688
26.328930 26.375000
11.523789 11.437500
17.523972 17.500000
16.781761 16.750000
All results match for block_size=128.
Checking correctness...
1.125032 1.054688
26.328930 26.375000
11.523789 11.437500
17.523972 …
```
=> Fix the unsupported block_size in matmul_backward_bias kernel 1

dataloader.h, dev/unistd.h
Tested with tinyshakespeare and fineweb on ubuntu 22 and windows 11.
- Moved glob() to dev/unistd.h
- Added mkdir support to dev/unistd.h
- changed long -> int64_t in dataloader.h
- put header guard in for dataloader.h
=> Add glob() for windows

dev/cuda/common.h, dev/cuda/layernorm_backward.cu, train_gpt2.cu
This one was absolutely horrible.
I ended up rewriting basically the entire kernel, even though in the end the deadlock fix might have been much simpler.
But hey, at least on my A4000, the new code is also 10% faster.
It does require more registers (not a problem at our block size, and with the launch_bounds requesting two blocks only), and more shared memory, though.
The change of the default input size in the dev file may have "broken" some of the earlier kernels, i haven't check which ones actually work with that size. Since it is the GPT2-XL size, and the one that is probably most problematic, I think it makes sense to choose it as the test case.
I've also made sure that kernel9 now just crashes instead of going into the deadlock. That is at least more easily debuggable behaviour.
=> Layernorm deadlock

train_gpt2.cu
`softmax_autoregressive_backward_kernel` does not use share memory in the kernel.
we do not need to launch the kernel with 256 bytes share memory, so remove it
=> `softmax_autoregressive_backward_kernel` does not use share memory in the kernel

dev/cuda/layernorm_backward.cu
1. Fix #428, the root cause: we are doing accumulation using the bfloat precision directly in atomicaddX, which results in a final error that is large.  The fix is to do accumulation in `float` (temp array allocated on device) and write the final accumulated result as `bfloat`.
2. spell the uint to `unsigned int` since uint isn't an actual type in C or C++ (comments from @ngc92 ).
After fix, kernel 2 passed.
```
Using kernel 2
Checking correctness...
dinp:
-0.559983 -0.562500
0.620476 0.621094
0.028621 0.028564
0.765740 0.765625
0.062205 0.062256
dweight:
-23.181511 -23.125000
-85.985672 -86.000000
-16.258125 -16.250000
-3.262060 -3.156250
59.474670 59.250000
dbias:
-30.434944 -30.500000
-93.241646 -93.500000
-41.022255 -41.000000
-13.087867 -13.125000
-56.647667 -56.500000
All results …
```
=> Fix "Mismatch of dweight at layernorm_backward.cu #428"

dev/cuda/benchmark_on_modal.py
The old script was not working due to deprecated API calls, it gave the following errors as shown in the picture below:
So I just updated those.
=> Modal benchmarking script updated to replace deprecated calls

pyrun124M.sh, train_gpt2.py
I believe we're getting the same results as `./run124M.sh` with this as of this PR:
```bash
torchrun --standalone --nproc_per_node=8 train_gpt2.py \
--input_bin dev/data/fineweb10B/fineweb_train_000001.bin \
--write_tensors 0 \
--model d12 \
--batch_size 32 \
--sequence_length 1024 \
--total_batch_size 524288 \
--dtype bfloat16 \
--compile 1 \
--tensorcores 1 \
--flash 1 \
--num_iterations 18865 \
--weight_decay 0.1 \
--zero_stage 1 \
--learning_rate 0.0006 \
--warmup_iters 700 \
--learning_rate_decay_frac 0.0 \
--overfit_single_batch 0
```
but only for 1 data shard. the dataloader is still not set up to do multiple shards.
=> pytorch parity v1

train_gpt2.cu
This CR is the first step in implementing the goal described in https://github.com/karpathy/llm.c/issues/478 to be able to reduce the memory footprint by adding an option to recalculate the layernorm activations in the backwards pass. The next step would be to create another kernel which is a smaller version of the layernorm forward kernel. Once I get a review from @ngc92 I will implement the second part of this PR.
=> First step in creating option to recalculate layernorm activations in backwards pass

train_gpt2.cu
make it obvious to the reader that the gelu backward operation is performed in-place, so we don't get any accidental "optimizations" in the future (like applying __restrict__ wrongly)
=> Inplace gelu backward

dev/cuda/classifier_fused.cu, train_gpt2.cu
Same issue as described in: https://github.com/karpathy/llm.c/pull/487
=> Removed unnecesary shared memory due to blockreduce using static defined shared memory

train_gpt2.cu
As per our Discord discussion:
Right now, in ZeRO stage 1, each GPU will compute a grad norm across all of its shards - but only a single shard has the correct numbers (after NCCL's reduce-scatter).
So what we should do instead is compute norm squared per shard that the device owns and then reduce (sum) them up across devices, take a sqrt and only then call AdamW kernel to update the params.
=> Fix zero stage 1 norm computation

train_gpt2.cu
We didn't free up CPU buffer memory.
Also no need to use `NUM_ACTIVATION_TENSORS` size_t slots for bw_act_sizes, we just need `NUM_BACKWARD_TENSORS`.
=> Fix mem leak

train_gpt2.cu
We're unnecessarily launching more threads than is necessary to compute the sharded param update.
Use `local_params` (subset of params that this shard is responsible for) instead of `num_parameters` (params in the whole layer).
=> Use local params for num blocks in adamw_kernel3

train_gpt2.cu
`bfloat16(0)` leads to an ambiguous conversion for older `nvcc`s, because it could either be int->float->bfloat or int->double->bfloat. Both would actually lead to the same result, but  the compiler doesn't know that, so we help it along by explicitly putting a float literal there.
=> fix compilation with older nvcc

dev/cuda/encoder_backward.cu
No need to repeatedly call backward on the CPU. Call it once and memset wte and wpe to the original state.
Also consistent with `crossentropy_softmax_backward` structure.
=> Remove redundant CPU computation in encoder bwd

train_gpt2.cu
I had a bug due to me not being fully aware what was used to init the model when I kick off the training script - so decided to make it explicit in the initial info we're printing.
`load_filename` only makes sense if we're not resuming from an existing checkpoint.
=> Improve start training print info

llmc/dataloader.h
Stepped through the code and convinced myself we don't need to clear inputs/targets in every single iteration, BUT:
We do need to initialize inputs/targets with all zeros (using calloc) as otherwise we might end up with ints that are outside of the vocab and that would mess up the forward pass (initial embedding logic, i.e. `encoder_forward`).
=> Refactor eval loader - remove 2 unnecessary malloc calls per iteration

Makefile, llmc/cudnn_att.cpp
- General: Removing all build artifacts - deletion of cudnn_att object files for "make clean" 
- Windows: Added #define NOMINMAX to the top of cudnn_att.cpp. No effect for linux/mac.
- Windows: Dialed down the warning level a notch on Windows - it was too noisy.
- Windows: Fixed the output for cudnn_att to skip the executable copy. No effect for linux/mac. 
Ran through CI already using the manual trigger: https://github.com/karpathy/llm.c/pull/483
=> Make clean fix and Windows cuDNN build fix

llmc/cublas_common.h, llmc/cuda_common.h, llmc/encoder.cuh, llmc/logger.h, llmc/matmul.cuh, llmc/tokenizer.h, llmc/utils.h
we are using some standard library facilities that are available because  some other header includes them, but we should be explicit about this so code doesn't break on compiler/lib upgrades that, e.g., reorganize some internal includes.
=> made implicit includes of standard headers explicit

train_gpt2.py
We have to zero the grads here because in the training loop we first do backward and only later we do zero grad.
This causes a duplicate "deposit" of gradients in the first training step which explains the divergence we had between PyTorch & C code.
=> Fix zero grads bug

train_gpt2.py
In our C implementation with reduce the loss properly before displaying it using print0.
In our PyTorch losses were not reduced that caused us to think we have a divergence between implementations.
I've put it outside of the grad accumulation loop for efficiency reasons.
=> Fix PyTorch DDP loss bug

.github/workflows/ci.yml
With this small CI change, it will enable the developer to trigger local CI workflows in VS Code and GitHub manually.
When you create a new branch in your fork (or repo) this will kick off a CI build. This first CI build causes GitHub to create a newly accessible CI trigger which allows you to subsequently trigger CI manually in VS Code using the GitHub actions extension OR in GitHub under the Actions menu.
This allows the developer to trigger CI and eventually pass CI while working in their branch before initiating a PR.
=> Trigger CI on new branch creation

dev/cuda/trimat_forward.cu
Made sure we're consistent in our notation:
* Use (B,T,NH,HS) only
* Constant are upper case
Added additional comments to clarify what each of the kernels is doing, including what the indexing operation is doing, e.g.:
annotate flat indexing: `const float* q = inp + b * T * C3 + nh * HS;`
with `Q[b][nh][:][:] = inp[b][:][0][nh][:]`
=> Refactor trimat

dev/cuda/matmul_backward.cu, dev/cuda/matmul_backward_bias.cu, dev/cuda/residual_forward.cu, dev/cuda/softmax_forward.cu
* Fix a few memory leaks in our CUDA examples
* Reduce memory by 2x in some kernels by reusing shared mem for both sum & max
* Refactor
=> Fix mem leaks, reduce memory, refactor

train_gpt2.py
Problem: Enabling the generation block crashes the program 
Solution: Change the variable names for x and y so that it does not affect downstream code
Testing: Runs as expected with tinyshakespeare
=> Fix periodic inference during training

llmc/attention.cuh, train_gpt2.cu
by deleting the grad activation struct, move some of the last pieces of memory to the forward pass
=> consolidate memory

llmc/mfu.h
Cherry picked the unproblematic change from the previous MFU PR.
I'm running on this H100 type so wanted to see MFU numbers.
=> Add H100 PCIe to MFU table

train_gpt2.cu
Due to Amdahl's law this optimization won't really matter (we only call this on the first call to `gpt2_update`), but for reference:
for a 124M model:
* `shard_num_parameters` (in zero stage 0, and single GPU setups) is 124M
* `shard.size` can be as small as 764 (layernorm shards)
So we're spawning 124M threads more than we need. :')
=> Fix copy and casting from spawning excessive threads

llmc/adamw.cuh, llmc/cuda_utils.cuh, train_gpt2.cu
Previously our stochastic rounding logic didn't have a unique seed for each of the parameters we're rounding. This PR fixes that.
In more detail, previously:
* we were passing the same seed for all `NUM_PARAMETER_TENSORS` (16) sections of the param buffer.
* the above combined with this logic (extracted to demonstrate the gist of the logic):
```
unsigned int seed1 = Get2dNoiseUint(threadIdx.x, blockIdx.x + blockDim.y * gridDim.y, seed);
unsigned int seed2 = Get2dNoiseUint(threadIdx.x, blockIdx.x, seed1);
```
and given that `blockDim.y * gridDim.y` is constant and equal to either `1*1` or `1*12` (depending on whether we deal with one of the 4 layers like wte, wpe, lnfw, lnfb or with transformer layers respectively) - meant that many params were getting the same `seed2`!
In particular for …
=> Fix stochastic rounding

llmc/fused_classifier.cuh, llmc/global_norm.cuh, train_gpt2.cu
We're currently not saving master weights as part of the state -> we lose some precision because otherwise when we resume we'll have to reconstruct the master weights by upcasting from lower precision params.
=> Add master weights to resume state

dev/cuda/matmul_backward_bias.cu
Fix such error that happens for CUDA 11.8 per discussion https://github.com/karpathy/llm.c/pull/558#issuecomment-2153054126
```
matmul_backward_bias.cu(151): error: no operator "+=" matches these operands
operand types are: floatX += float
dbias[idx] += block_sum;
```
=> Fix the compiler warnings and errors

llmc/global_norm.cuh, requirements.txt, train_gpt2.cu
The previous assert logic was too restrictive as it depended on the number of layers of the model and the specification of the GPU (num of SMs & max number of threads per SM).
This PR fixes that. Tested, determinism works.
We can refactor this code afterwards, as it's ugly / I don't like the design:
`get_max_num_block_sums` is coupled to `global_norm_squared` if latter changes the former needs to follow, which is perfect for introducing bugs.
=> Hotfix - proper handling of max num of block sums

dev/cuda/fused_residual_forward.cu, dev/cuda/layernorm_forward.cu, llmc/layernorm.cuh
I ran kernel 5 under `/dev/cuda/` (`./layernorm_forward 5`) on both RTX 3090 and H100 systems and it's faster on both of them.
Numbers:
kernel 3, optimal block size on:
- RTX 3090 → 32 (689.11 GB/s)
- H100 → 128-512 (1191.38 GB/s)
kernel 5, optimal block size on:
- RTX 3090 → 256 (773.13 GB/s)
- H100 → 256 (1244.5 GB/s)
It also seems to be more predictable in terms of what the optimal block size is, whereas kernel 3 perf varies a lot between these 2 systems.
Note: again, as per Ahmdal's law we're calling layernorm forward only once in our forward pass, the rest we are using the residual fused kernels. But still, it's a low hanging fruit unless I am missing out on some context as to why we didn't use kernel 5 here? Omission or by design? Is it because the way we're computing variance in …
=> Use faster kernel for LayerNorm forward

llmc/cuda_common.h, llmc/dataloader.h, profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
Extends the test script to validate determinism.
Some thoughts:
* With C memory management, it is quite easy to introduce memory leaks, e.g., loading from checkpoint twice without freeing in the middle causes a leak. To be somewhat defensive against this, I added a check that  validates that the pointer is null before allocating; which doesn't actually work, because the pointer value will be whatever random garbage was at that memory location before. In the end, I ended up requiring a separate gpt2_init call in front of either checkpoint loading or random generation.
* As the test script currently doesn't use the data loader, there are now some ugly ifdefs inside state saving/reading.
I did test cherry-picking this commit into an earlier version of the code, before the recent fixes, where …
=> Check determinism in CI

llmc/dataloader.h, test_gpt2.cu
Modified the code a bit in order to remove the hacky patch due to the original off by 1 error:
* Sample index should start from -1 (both after reset & shard advance)
* No need to do next batch call inside resume
Similarly for test:
* No need to call next batch before calling save state
* Inside the for loop we first load data and then do fwd/bwd/update as opposed to at the end
=> Fix dataloader & determinism testing

llmc/encoder.cuh
https://github.com/karpathy/llm.c/pull/597 provided unique seeds to adamw update.
This PR does the same thing for the encoder backward which is the only other place where we do stochastic rounding.
=> Fix stochastic rounding in encoder backward kernel

test_gpt2.cu
* Stricter FP32 logit accuracy
* Much stricter FP32 loss accuracy
* Much stricter FP32 grad tensor accuracy (and somewhat stricter 16 bit accuracy)
* Copied over new expected loss values from PyTorch (they're a bit different and I took all 6 decimal points and not just 4)
* Also adapted our test logic to round loss to 6 decimal points
Regarding grad tensors: back when Andrej hardcoded the thresholds we had a bug in PyTorch that led to a bigger discrepancy between our PT vs C code - now that that's fixed we can be really strict and use `1e-6f` here.
=> Stricter FP32 tests

dev/test/test_dataloader.c, dev/unistd.h
- test_dataloader.c - In moving this over to CI, ran into a couple of issues accessing past the calloc'ed buffers.
- test_dataloader.c - added some const values to quiet warnings
- test_dataloader.c - added unistd.h for windows
- unistd.h - small cleanup - remove warnings for windows
CI passes.
@karpathy @ngc92  - can you please check the changes in test_shuffled and test_multiprocess_shuffled. We were accessing one token past the end of the buffer. Thank you.
Revised with comments below.
=> Bug fixes and warning fixes for test_dataloader.c

test_gpt2.cu
Our CI is using A4000 GPUs that didn't caught some of the tight grad tensor thresholds I've set in https://github.com/karpathy/llm.c/pull/614 
Relaxing a few of these reported by @rosslwheeler
On a side note: @karpathy would be cool to understand exactly how many GPUs we've got as CI runners, and potentially ask if we can trade a few of these for some different GPUs. :) (one can but hope)
=> Relax grad tensor thresholds in tests

.github/workflows/ci_gpu.yml, dev/test/device_file_io.cu, llmc/cuda_common.h, llmc/utils.h, test/device_file_io.cu, test_gpt2.cu, train_gpt2.cu
handling disk io for checkpointing with cuda streams is a nontrivial task. If you're  not careful, you can easily get broken code (need to wait for data to be on the CPU before you can start writing the buffer to the disk), or synchronous behaviour (because memory is not page-locked, so async copies are not possible)
Therefore, this PR introduces two new utility functions to do the disk <-> device data transfer.
In addition to being less error prone and reducing code duplication, this also gives us a single point at which we can implement double buffering to actually get an overlap between device transfer and disk writes; with an added bonus that we no longer need to allocate giant CPU-side arrays (think: 8 A100s on the same node each wanting to write 40 GB model state; we'd attempt to …
=> Utilities for cuda streams + disk IO

Makefile, README.md, llmc/zero.cuh, profile_gpt2.cu, scripts/multi_node/run_gpt2_124M_fs.sbatch, scripts/multi_node/run_gpt2_124M_mpi.sh, scripts/multi_node/run_gpt2_124M_tcp.sbatch, test_gpt2.cu, train_gpt2.cu
Instead of mixing NCCL & Open MPI during training: let's transition to using only NCCL. To the best of my knowledge there are no downsides here, they're equivalent and speedwise i couldn't observe any difference.
By doing this we scope down our MPI dependence to `multi_gpu_config_init`.
Context: why are we trying to reduce dependence on Open MPI?
`slurm-wlm` package - which is the easiest and thus likely the most frequent way folks setup their slurm clusters - dropped PMIx support which means we can't use slurm in a multi node setup together with Open MPI.
Regarding `multi_gpu_config_init` we have a few options as far as i can tell:
* Keep using MPI (but as mentioned slurm users won't be able to run llm.c in multi-node setup)
* Transition to logic where we synchronize on file system …
=> MPI/TCP/FS for NCCL-init

llmc/cuda_utils.cuh
After the conversation with Squirrel (author of the noise rnd generator we're using) it might be a good idea to cast the intermediate computation to uint to avoid dealing with ints having UB (undefined behavior) overflow.
See [discord thread](https://discord.com/channels/1189498204333543425/1253010838596354189/1253010903176314970).
=> Cast Get2dNoiseUint computation to uint

Makefile
To run the file sharing NO_USE_MPI build.
=> Add missing MULTI_GPU compiler flag

train_gpt2.cu
checkpoints are either MINOR or MAJOR and minor checkpoints get deleted with a rolling window. This is an optimization that will allow us to save state more often, but preserve disk space overall. And if we ever see loss spikes and such, it is easier to reset the state to an earlier checkpoint that is more recent
Introduces two new flags:
```c
fprintf(stderr, "  -nk <int>   max number of checkpoints to keep in the directory, removing old ones (0 = disable, default)\n");
fprintf(stderr, "  -nm <int>   every how many step checkpoints are considered major? major checkpoints never get deleted.\n");
```
Example usage:
```
-n 20 \
-nk 3 \
-nm 100 \
```
This will write checkpoint every 20 steps, only keeps up to 3 minor checkpoints in the directory at any time, except every 100th checkpoint is …
=> rolling checkpoints

llmc/cuda_common.h, llmc/cuda_utils.cuh, llmc/fused_classifier.cuh, llmc/global_norm.cuh, llmc/matmul.cuh, llmc/utils.h, profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
Moves loss calculation to backward, and ensures  we can do more on-device reductions and fewer host<->device transfers.
Also enables a micro-optimization, that validate does not calculate dlogits anymore.
=> On-device reductions

dev/test/test_outlier_detector.c, llmc/outlier_detector.h, profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
still TODO:
- track grad norm in addition to loss (do we have to split the `gpt2_update` function)
- add argparse option to monitor loss and grad norm for outliers (e.g. z > 3)
- add handling of instabilities (e.g. if z > 3, skip update)
- possibly: instead of skipping update we could EXIT_FAILURE, and when -y 1 resumes the optimization from last checkpoint, we could try to somehow advance the DataLoader past the point of instability (this is what PaLM did)
=> add outlier detector, test for it, and start tracking z score of loss

Makefile
I am experimenting with cross-compiling the program to an nvidia device and bumped into the need for this change.
During the openMPI check, the MULTI_GPU define slinks in.
=> Makefile: Respect the NO_MULTI_GPU

llmc/cudnn_att.cpp
cuDNN Frontend 1.5 released on June 13th added a new setting to make their backward algorithm deterministic which is disabled by default:
- https://github.com/NVIDIA/cudnn-frontend/commit/47d800ccd9449e1bbc255d64d794ae88d99b043d
- https://github.com/NVIDIA/cudnn-frontend/blob/main/docs/operations/Attention.md
Testing on cuDNN Backend 9.2 + cuDNN Frontend 1.4 (where that setting is not available) revealed that cuDNN Backward was *not* deterministic at large batch sizes. As small batch sizes seem to always be deterministic, this would not have been caught by our test_gpt2cu tests.
This is despite NVIDIA documentation implying that it should have been deterministic, as their lists of non-deterministic cases did not include attention backward. There is a remark in the [cuDNN Backward release …
=> Make cuDNN deterministic for Flash Attention backward

llmc/fused_classifier.cuh, llmc/layernorm.cuh, train_gpt2.cu
This is currently based on #635 , because there we ended up needing to reduce losses in  bf16.
So this PR first does some malloc-and-point generalization for allowing multiple dtypes, and then changes layernorm statistics and losses to fp32. 
With layernorm stats in fp32, we can reliably avoid their recomputation even if we recompute the layer itself, and these tensors are still tiny, so it doesn't cost us much.
=> Mixed dtypes

.github/workflows/ci_tests.yml, dev/cuda/Makefile, dev/cuda/layernorm_forward.cu, dev/test/Makefile, llmc/dataloader.h, llmc/rand.h, train_gpt2.c
- New CI tests file - added dataloader test and ptx/sass file generator to it. 
- Cuda Makefile - added capability build from main Makefile. Added support for ptx and sass output files. 
- layernorm_forward.cu - remove #define (was already in header file)
- dev/test/Makefile - new file (based on main Makefile) for running tests
- dataloader.h - added casts to remove compiler warnings
- rand.h - removed unused parameter. Added casts to remove compiler warnings.
- train_gpt2.c - rename unsigned long long to uint64_t.
Pre-verified with CI.
=> CI Dataloader test and ptx/sass file generator

profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
We got a similar bug introduced for similar reasons in our main code as before in PyTorch code:
Due to the fact that zero grad happens after the backward step instead of immediately before we do backprop.
Here we have `gpt2_validate` that periodically runs before our training loop and "contaminates" the `model->acts.losses` which is part of our "grad state" and which we start depositing on top of in the backward pass (valid state is all zeros).
The reason we don't see the spike in the 0th step is because we run zero grad in the 0th step of the training inside the `gpt2_backward_and_reduce`, and set the grad state to correct state just before we run backprop.
Instead we should just always do it to protect the grad state from other parts of the code that can contaminate it. This makes the …
=> Fix periodic loss spikes

llmc/attention.cuh, llmc/cublas_common.h, llmc/matmul.cuh, test_gpt2.cu, train_gpt2.cu
In preparation for FP8, this replaces all cuBLAS calls by cuBLASLt which is now wrapped by a single matmul_cublaslt() function.
It also adds support for GELU fusion which can be controlled on the command line with "-ge": 0 for disabled, 1 for forward only, 2 for forward+backward. The default is 2 is for H100+ and 0 for older GPUs based on seeing regressions on RTX 4090 previously _**but you might want to consider disabling it by default before merging due to the following:**_
In terms of accuracy and validation loss, the fused GELU seems very slightly worse than ours (how/why?!) which is not ideal especially when combined with GELU recomputation since it means the activations used for the backward pass won't be bit-for-bit identical to the ones used in the forward pass.
It's hard to tell …
=> Matmul refactor using only cuBLASLt + GELU Fusion

train_gpt2.cu
I'm not sure how we missed this but we don't actually need these tensors at all for the backward pass at all! Possibly this wasn't the case when residual/layernorm/recompute were implemented differently, or I'm missing something? Either way, it's a significant GPU memory saving.
=> Remove per-layer attproj and fcproj activation tensors

llmc/utils.h, llmc/zero.cuh
Add socket close check functions - consistent with the rest of the codebase.
=> Add check versions of functions

train_gpt2.cu
The inference sanity checks currently process all (B,T) despite only needing (1,64) by default.
This PR is bit-for-bit identical to previous versions while reducing this to (1,t) where t is rounded up to the next multiple of 256 - that value was selected so cuDNN (currently) uses the same algorithm as for the full 1024, otherwise it might give slightly different results (which shouldn't matter in practice but it's a nice property to keep if we can, and it's still massively faster than our current inference path).
It also fixes a potential non-determinism issue for the non-CUDNN path in the process: [cudaMalloc does *not* clear the memory](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g37d37965bfb4803b6d4e59ff26856356), so in theory we …
=> Faster inference by changing (B,T) to (1,t)

README.md
Add a README link under related related projects for gpu.cpp under WebGPU C++.
For background - gpu.cpp is a new project I've been working on. It's a small library for writing portable GPU code in C++ that works across vendors by using a native (ie non-browser) WebGPU implementation (Dawn from Google).  It aims to be a general-purpose library, but will also port the `dev/cuda` kernels to make llm.c kernels broadly available as WebGPU kernels using the WebGPU Shading Language (WGSL).
Some relevant discussion here: https://github.com/karpathy/llm.c/discussions/670
=> Add a README link under related related projects for gpu.cpp under WebGPU C++

.github/workflows/ci_gpu.yml, dev/loss_checker_ci.py
- Modified the train_gpt32 (FP32) run with gpt2_124M.bin to add requested parameter changes in CI
- Added a check for the loss to see if it varies > 5 percent. This is configurable - so we can change this to a lower value if that's more appropriate.
Tested in CI
=> Adding CI check for exceeding loss tolerance

README.md
From discussion #572 , supporting initial Habana Gaudi2 accelerator port of llm.c (TPC)
cc @karpathy
=> Add Habana gaudi2 tpc kernel link

llmc/cuda_utils.cuh, profile_gpt2.cu, test_gpt2.cu, train_gpt2.cu
* consolidate model parameter allocation to a single source location
* made gradient buffer accumulation eager
* moved encoder determinism helper buffers so that they are eagerly allocated by forward -> backward is now free of mallocs
* moved dtype helpers into utils file
=> Model init cleanup

train_gpt2.cu
Due to some parameters in the GPT-2 7.3B model being quite large, the current `llm.c` code has integer overflow issues. This is because it uses a 32-bit `int` to store the number of bytes for weights and perform `malloc` operations. These large values exceed the maximum value that a 32-bit `int` can hold, causing overflow.
This PR changes to use `size_t` in `gpt_build_from_descriptor`, making the type consistent with `param_elements` in the code: https://github.com/karpathy/llm.c/blob/72698a5ba32482789fb3b14fcff8b6b6d20931d9/train_gpt2.cu#L313
=> Fix integer overflow by using `size_t` for parameter sizes.

dev/cuda/Makefile, dev/cuda/permute.cu
This PR primarily focuses on the educational aspects of llm.c. I observed that permute kernels are not present in dev/cuda directory, so I have added the implementation showing a small example of permuting a 4d tensor. Additionally, also have included explainations on how the permute operation works, along with guidance on developing a mental model for understanding permute operation while working with threads.
=> Added permute kernel in dev/cuda

llmc/adamw.cuh, train_gpt2.cu
This is fully deterministic for new checkpoints where the new rng_state_last_update is saved, so that stochastic rounding from master weights is done with the exact same seeds (while restoring the actual final rng_state again afterwards, in case anything else changed it between that update and saving the checkpoint).
In the case where we are resuming from a checkpoint (not just a regular model file) and we have master weights, this simply skips loading the weights from the checkpoint completely, so it doesn't matter if they are not even the right number of bytes.
It should be useful to check if FP32 helps with runs exploding, and going forward it will allow FP8 runs to not care too much about what format the non-master weights are saved, so we don't need to worry about changes breaking …
=> Restore from master weights (& allow restoring from a checkpoint of different precision)

dev/cuda/Makefile, dev/cuda/permute.cu
Just another minor PR to "standardize" the newly added permute kernel to the same conventions adopted for the other kernels.
=> chore(dev/cuda): use common utils in permute kernel

train_gpt2.c
Realized we do activation size computation inline, so changed it to be consistent with how we compute parameter sizes. It's more readable than bloating the fwd pass.
=> Refactor C code

Makefile
This improves compile times by:
1) Using nvidia-smi instead of __nvcc_device_query (the latter was wasting >1 second per build on a 1xH100 system!)
2) "--threads=0" allowss NVCC to use multithreading for some things (seems to improve compile times by ~5% locally.)
3) Making -O3 configurable with the FORCE_NVCC_O parameter (O0 improves compile times by >30% but significantly hurts run times; -O1 seems like a good compromise when iterating on some code.)
(1) and (2) reduce compile time with cuDNN from ~9.2s to ~8.1s.
(3) with O2/O1/O0 reduces it further to ~7.7s / ~6.5s / ~5.4s.
=> Improve compile time (simple makefile changes)

dev/data/README.md, dev/data/data_common.py, dev/data/fineweb.py, dev/data/tinyshakespeare.py, dev/data/tinystories.py, train_llama3.py
commit on top of @gordicaleksa PR that makes a bunch of bugfixes
- be more explicit with treatment of EOT token
- be careful with API for AutoTokenizer
- bugfix on dtype in fineweb.py
- use model_desc instead of model because the latter is usually a nn.Module
- few more
=> Gordicaleksa fix dataloader2

dev/data/README.md, dev/data/data_common.py, dev/data/fineweb.py, dev/data/tinyshakespeare.py, dev/data/tinystories.py, requirements.txt, train_llama3.py
Add LLaMA 3 tokenization support for all our datasets:
1) tiny shakespeare
2) tiny stories
3) fineweb
=> Fix llama 3 data loader

llmc/cuda_common.h, llmc/cuda_utils.cuh, train_gpt2.cu
Use cudaMallocManaged to allocate optimizer states if we run out of device memory, so we can still train (slowly) even if we cannot fit the optimizer state
This is based on #694 , which should be merged first
=> Allocate managed memory if device memory runs out

train_llama3.py
Minor refactor.
Some refactoring took from [nano-llama 3](https://github.com/karpathy/nano-llama31/commit/a368a5218f98da0712283a6d674e0a76705c8a58).
=> Minor LLaMA 3 refactor

Makefile, llmc/adamw.cuh, llmc/cuda_common.h, llmc/cuda_utils.cuh, train_gpt2.cu, train_llama3.cu
Seems to work extremely well for tinyshakespeare on both GPT2 & Llama3.
For GPT2, val loss with BF16 m/v and *no master weights* is actually a tiny bit lower than FP32 m/v + master weights! (after 74 steps: 3.499682 vs 3.506536... this might just be noise of course, but it's encouraging)
This requires using the new Makefile option "OPTIMIZER_LOW_PRECISION=1" - it would be much messier if it was a command line option, like this it barely affects the code (the stochastic rounding gets optimized away automatically when it's disabled, since FP32 stochastic rounding is a no-op).
=> BF16 opt state (m/v) with stochastic rounding (Llama3 branch)

.github/workflows/ci.yml, .github/workflows/ci_gpu.yml, Makefile, llmc/zero.cuh, requirements.txt, test_llama3.cu, train_llama3.cu, train_llama3.py
This implements the minimum necessary changes to get an implementation of LLama3 that is functional.
Key fixes compared to the current llama3 branch:
* ignore bias terms during backward
* ensure learning rate matches pytorch reference
* fix gradient checking (#801)
When trying to set up CI, we run into the problem that even the 1B model is too large to fit for training; I've tried two different things:
a) run reference code with `--device=cpu`. This works, but we see numerical differences quite prominently, would need to increase tolerances by ~10x for fp32 mode
b) use torchao's CPUOffloadOptimizer. Works, but introduces another dependency on the python side. ~Also changes the numerics, but only for the optimizer, so it doesn't break the gradient step.~ EDIT: CPUOffloadOptimizer is not …
=> LLama3 MVP

test_gpt2.cu
The order of tensors inside our buffer differs from the order in which we run our gradient checks.
As the layout of the reference and test tensor are the same, we're still comparing corresponding elements, but the mapping of (named) tensors and tolerances into the buffer is wrong; potentially, we didn't compare some elements, and compared others twice.
This PR reorders the tensor names and thresholds to correspond to our actual model definition, and adapts the thresholds accordingly (this is much better visible by looking at the diff of just the second commit). For layernorms, the thresholds had to be increased quite a lot (maybe it should have been suspicious that the last LN needed so much larger tolerances than the others; now they're more equal), but for some other tensors we could …
=> Fix gradient tests
