karpathy/llm.c

- requirements.txt
Added a missing requirement - transformers
> fix: add transformers to requirements.txt

- Makefile
- train_gpt2.c
Hi,
Amazing project :D 
Thank you! 
I needed this to work for my mac, I didnt have omp
> Minor correction for openmp check

- dev/cuda/layernorm_forward.cu
an implementation of layer-norm that doesn't require shared memory or other intermediate buffers. On my A4000, I get  a speedup from 192 GB/s for kernel two at block size 64 to 303 GB/s for this kernel at block size 32.
Not sure if you are OK with this code, since technically, it isn't pure C, making use of namespaces and templates. I would say it's still pure CUDA, though, since these things do come directly from CUDA, not any additional library.
> fully fused layer-norm kernel

- train_gpt2.cu
Unfortunately the performance gain is ~noise because the amount of data to transfer is currently negligible, but it's theoretically still the "right" way to do it performance-wise. Also moves the malloc/free cpu_losses out of the main loop.
See: https://developer.nvidia.com/blog/how-optimize-data-transfers-cuda-cc/
> Use cudaHostMalloc for inputs/targets and cpu_losses

- train_gpt2.cu
Large perf gain as TF32 was only enabled for cuBLASLt and not cuBLAS by mistake.
Performance on A100:
- PyTorch: 23.6ms (version 2.1 so probably a bit faster on 2.2)
- Before: 48.2ms
- After: 25.1ms
> Fix cuBLAS to use TF32 with pre-initialised handle

- dev/cuda/classifier_fused.cu
This fixes the tests for the fused backward classifier pass so that they have a more interesting probability distribution that is not almost uniform (close to zero);
this exposes an error in  the existing kernel original spotted by @ademeure , which is now fixed, too
> ensure valid test cases and incorporate fixes by @ademeure

- train_gpt2.cu
Make the attention backward over 10x faster by ensuring we have enough threads, and  accumulating in registers
> fix accumulation and load balancing

- dev/cuda/layernorm_backward.cu
- train_gpt2.cu
gives 10x speedup, removing this kernel as a bottleneck in backward
> warp-wide reduction for layernorm backward

- dev/cuda/layernorm_backward.cu
https://github.com/karpathy/llm.c/issues/147 
script execution as normal after the change.
> Constness fix layernorm_backward.cu

- train_gpt2.cu
reuse memory buffers across layers during the backward pass
> Memory savings by reusing the same buffer across layers in backward

- dev/cuda/attention_backward.cu
- train_gpt2.cu
We're hitting diminishing returns, so this is probably going to be last update for this kernel from me for a while. I really like the simplicity of kernel 7, but  even kernel 8 isn't so bad, and we do get 5-10% speedup from this on my system.
> Some more optimizations for the backward attention kernel

- README.md
> README: Adding C# port ref

- dev/cuda/adamw.cu
https://github.com/karpathy/llm.c/issues/147
> const-fix adamw.cu and fix the warning C4305: 'initializing': truncation from 'double' to 'float'

- dev/cuda/attention_forward.cu
This is for the educational part of this repo, and not for getting maximum speed. 
It tries to stay as close to the CPU version as possible while still being "reasonably" efficient. For me, it appears to be about 3x slower than the cublas versions, which isn't too bad considering the (IMO) simplicity of the code.
> slow attention kernel that demonstrates a direct translation of the CPU code

- profile_gpt2cu.py
I think this should be more or less the script you wanted :)
The read/write and instruction numbers are mainly included so we can print out these cool stats at the end. If you wanted to identify bottlenecks, the bandwidth% would be much more helpful, but IMO, for that, you really should just open the file in nsight. Here, I just wanted to visualize how much work of which kind gets done in the different parts of the network.
> profile and print out some nice stats

- dev/unistd.h
Adding this into the dev/ directory. If we decide to create a /platform directory, we can move it there.
> Adding unistd.h for Windows in /dev directory

- test_gpt2.c
- train_gpt2.c
const changes to help with Microsoft compiler OpenMP 5.2 support
> const changes to help with Microsoft compiler OpenMP 5.2 support

- train_gpt2.py
The train_gpt2.py is broken at the moment.
This is a fix for that. 
These things I found to be wrong and have fixed:
- gradients are not computed which results in 
```
File "/Users/runner/work/llm.c/llm.c/train_gpt2.py", line 403, in <module>
write_state(model, x, y, logits, loss, "gpt2_124M_debug_state.bin")
File "/Users/runner/work/llm.c/llm.c/train_gpt2.py", line 27[9](https://github.com/Ricardicus/llm.c/actions/runs/8775693842/job/24078315777#step:6:10), in write_state
grads = {name: param.grad.cpu() for name, param in model.named_parameters()}
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cpu'
```
- fused is used when the device is not cuda which breaks down on cpu and mps 
- attempting to write data that is not on the cpu to disk
- …
> train_gpt2.py: fix for conditional use of fused and for computing gradients

- .github/workflows/ci.yml
- Makefile
- train_gpt2.py
This is a start, but this workflow does the following:
- builds and tests on CPU with and without openMP (macos and ubuntu)
- builds the CUDA files (does not test them)
Ideally one would like to test the CUDA also, but it is hard to do this.
I think it would be possible to use the virtual GPU drivers from NVIDIA, but I don't know
how to do this and I think that rabit hole can be left uninvestigated for now. This is a start!
It will run on PRs and pushes to the master branch.
> Adding a github workflow

- README.md
Added a reference implementation in zig of the llm.c
> Added ref to the zig port 

- README.md
Add link to go port of this project. 
Forward pass + backward pass works, only CPU and there's a whole bunch of room for optimisations but it works in wasm, so that's cool. 
Also in the I've implemented a simple [trie data structure](https://github.com/joshcarp/llm.go/blob/040d8f42dfb82e1a487a652a1dea73d429ed0f12/tokenizer.go#L79) for encoding text into tokens and have transcribed it back into C and will raise a PR if there's an appetite for it. I have no idea how it's actually done in tiktoken/anything else but it works.
> Add reference to llm.go in description

- train_gpt2.c
- train_gpt2.cu
@ademeure this fixes the issue but ... i'm not sure about how to more generally handle int vs size_t everywhere in the code in a principled way.
> candidate fix for int overflow

- train_gpt2.cu
Removing two helper functions that are no longer used
> Remove unused helper functions

- train_gpt2.c
- train_gpt2.cu
- train_gpt2_fp32.cu
- utils.h
function that are (or should be)  shared between our three training scripts moved into a common header file
> moved checked helper functions into a separate file

- train_gpt2.cu
When doing the conversion of 32 to 16 bit data types adding the templates helped clarify which inputs needed to share data types but is no longer needed and this makes it easier for developers now to tell what data types are being passed into the kernels.
Had this mostly written up before the chat in the discord about the decision of whether to keep mixed precision so thought I might as well make the PR
> Removed templates from kernels to clarify data types and simplify code

- dev/cuda/common.h
- dev/cuda/layernorm_backward.cu
- test_gpt2.cu
- train_gpt2.cu
- train_gpt2.py
minor fixes on top of https://github.com/karpathy/llm.c/pull/272
creating PR just to get CI sign off
> Ademeure layernormbf16 3

- .github/workflows/ci.yml
- dev/cuda/Makefile
Might as well build the example kernels up here in the CI!
> Adding the example kernels to CI

- Makefile
- README.md
- dev/cuda/attention_forward.cu
- profile_gpt2.cu
- test_gpt2.cu
- train_gpt2.cu
- train_gpt2.py
Builds on top of PR https://github.com/karpathy/llm.c/pull/322
Additional small fixes to merge cudnn support, and with it flash attention
> feature/cudnn for flash-attention

- dev/cuda/Makefile
- dev/cuda/adamw.cu
- dev/cuda/attention_backward.cu
- dev/cuda/attention_forward.cu
- dev/cuda/common.h
- dev/cuda/gelu_forward.cu
- dev/cuda/layernorm_backward.cu
- dev/cuda/matmul_backward.cu
- dev/cuda/matmul_forward.cu
- dev/cuda/trimat_forward.cu
> mixed precision utilities for dev/cuda

- train_gpt2.c
Similar to the `.cu` version, in `.c` a new function is defined for parameter size table.
This will be useful for reuse with e.g. initializing weights from
scratch instead of a checkpoint for the issue #243.
> Refactoring parameter size filling

- train_gpt2.cu
adds an optional second copy of the weights in fp32 precision
~TODO missing free~
> option to keep weights as fp32

- dev/cuda/matmul_backward_bias.cu
just the basic version for now, but converting to f128 should be straight-forward
> bias backward kernel that will use all available threads

- train_gpt2.cu
also, we don't need to touch the other buffers in  zero_grad, these are anyway overwritten multiple times during backward
> fixed activation gradient resetting for backward pass

- README.md
I also sorted the ports alphabetically.
> Adding a java port of the project

- train_gpt2.cu
- train_gpt2_fp32.cu
1. remove the duplicated #include <assert.h>
2. remove the unused #include <ctype.h>
> Remove the duplicated #include <assert.h>

- train_gpt2.cu
provide our own version of missing functions
> make things compile with nvcc11

- dev/cuda/Makefile
Makefile type fix: move gelu_backward to backward block
> Makefile type fix: move gelu_backward to backward block

- dev/cuda/classifier_fused.cu
> Minor update on the classifier_fused.cu

- profile_gpt2cu.py
This adds 2 new stats (+an overall efficiency metric) to the profile_gpt2cu.py script that make it much easier to evaluate the relative efficiency of kernels (before potentially going deeper with Nsight Compute).
Here are the results on my RTX 4090 where the the maximum value of the Tensor Core Utilisation counter is 50% and while the theoretical peak bandwidth is 1008GB/s, this is impossible to reach in practice, so I am using the "highest bandwidth of any kernel" as the baseline for 100% bandwidth (in my professional experience, good luck getting near 100% out of any modern memory controller and cache hierarchy no matter what, while tensor cores can trivial reach their theoretical peak if you just feed them the same data over and over again).
This was taken while optimising some of the …
> Add DRAM BW, Tensor Core Utilisation, & Efficiency Stats

- Makefile
Small cleanup changes on the build for cudnn. Added Windows support for cudnn. Tested on Ubuntu 22.04 and Windows 11.
- Command line and Windows changes - (top part of the Makefile) Change from := to ?= so we can override the CUDNN_FRONTEND_PATH from the command line. Fixed the locations for the CUDNN_FRONTEND_PATH for Windows and Linux to search for both $(HOME) or current directory)
- cuDNN Windows support (in the middle of the Makefile)
- Makefile cleanup - (lower part of Makefile) change "$<" to "$^" to pull in ALL of the dependencies. This eliminates the need to put (NVCC_CUDNN) on the recipe line. Removed linker files from object file compilation recipe. Added $(NVCC_CUDNN) to list of targets. That way it gets deleted on a make clean.
> cuDNN makefile changes

- train_gpt2.cu
> Fix incorrect GPU assignment in multi gpu setup

- train_gpt2.cu
This commit is the fix by ademeure described in the comment below:
https://github.com/karpathy/llm.c/pull/382#issuecomment-2100895501
To reproduce the following bug:
https://github.com/karpathy/llm.c/pull/382#issuecomment-2100648148
First switch to gpt2-xl for tinystories with the following three commands:
```
python prepro_tinystories.py  # download tinystories
sed -i 's/from_pretrained("gpt2")/from_pretrained("gpt2-xl")/' train_gpt2.py  # select gpt2-xl
python train_gpt2.py --input_bin data/TinyStories_train.bin --batch_size 1  # Prep the large model binaries
```
Now you can compile and try the code with or without the fix.  On an H100 machine I use the following command:
```
train_gpt2cu -i data/TinyStories  -b 10 -x 100  # gets 230k/s on one H100 node of 8 GPU
```
> Allow the code to train gpt2-xl

- dev/cuda/Makefile
- dev/cuda/attention_forward.cu
- dev/cuda/classifier_fused.cu
- dev/cuda/common.h
- dev/cuda/encoder_forward.cu
- dev/cuda/fused_residual_forward.cu
- dev/cuda/gelu_backward.cu
- dev/cuda/gelu_forward.cu
- dev/cuda/layernorm_backward.cu
- dev/cuda/residual_forward.cu
- dev/cuda/softmax_forward.cu
- train_gpt2.cu
cherry-picked and cleaned up. No longer any template magic; just moved the floatX definitions into the common file
> Fused layernorm+residual V2

- cudnn_att.cpp
- Simplify graph cache and usage of cudnn.
- Fix failures in H100
> simplify usage of cudnn

- README.md
@karpathy first of all thank you very much for creating this project and all the other content you produce for free. 🙏 I have previously ported micro-grad to C# too and here I link to my port of `llm.c` to C#. I started this before any CUDA code so mine is CPU only currently and I had no idea of the other port. Focus has been on adopting to .NET standards and making it easy to simply clone and run. Feel free to try it out, it's very easy ;)
I am very much looking forward to llm.c including all aspects of GPT2 training weight initialization and tokenization etc.
Regarding tokenization you might find inspiration in .NET https://github.com/dotnet/machinelearning/tree/main/src/Microsoft.ML.Tokenizers for that, and .NET has this feature that it can source generate code for regex expression, …
> Add Llm.cs by nietras to README

- .github/workflows/ci.yml
This is ready to go.
Change notes:
- 	Add Windows build/test to CI matrix build
- 	Add Cuda Windows build
- 	Replace v3 checkout actions to v4 per GitHub recommendations
> Add Windows to CI

- train_gpt2.cu
- train_gpt2.py
Doesn't work. On master, we reproduce our Python script (almost) exactly by running:
```
make train_gpt2cu NO_MULTI_GPU=1 USE_CUDNN=1
./train_gpt2cu -b 4 -t 64 -l 1e-4 -v 200 -s 200 -a 1 -x 10
```
But doing this on this branch fails and the loss stagnates, something is wrong with the optimization.
Running an actual training loop, the loss does not decrease.
debugging...
> [wip] gradient accumulation, another attempt

- dev/cpu/matmul_forward.c
@karpathy, Can we setup a dev/CPU area to play around?
@ngc92 I added your new matmul_forward as a first CPU kernel example.
> Setting up dev/cpu area with the first matmul_forward.c

- README.md
> Add link to AMD fork

- test_gpt2.cu
*  tighter tolarances
*  relative tolerance based of bf16 epsilon
*  less verbose output if all is OK
I've checked these tolerances with both RTX 4060Ti and A4000 (which do give different errors, sometimes substantially). Values are chosen as tight as possible such that on neither GPU we exceed 90% of the error threshold, to allow for some more variety across GPUs.
> improved numerical error checking

- .gitignore
- dataloader.h
- dev/data/data_common.py
- dev/data/hellaswag.py
- train_gpt2.cu
This was not super easy but ... first draft, apparently this works. needs cleanups, and also we are not yet utilizing the full batch dimension. we actually have to load in multiple examples and fully utilize batch.
TODOs still before merging:
- remove TODOs and prints and debugs
- make HellaSwag eval optional of course
- fully utilize the batch dimension by packing in more examples. Right now we only utilize the first 4 rows of the `BxT` batch.
But it does work, including multiple GPUs, and matches PyTorch reference.
> HellaSwag eval in C

- README.md
I'm not sure if a PR is the proper way to ask for adding a reference to my port... Anyway, porting was fun and educational. Thx for sharing your work.
> A Swift port of this project

- train_gpt2.cu
- train_gpt2.py
for 2D tensors, as done in GPT series and in general too. this forces us to break up our adamw kernel again into one call per tensor, so there is a small throughput hit, of about 0.5% for me. but we have to break up this kernel in near future anyway.
GPT-3 reports using weight decay of 0.1 btw.
I verified that:
- changing the weight decay in both C and PY has an effect on the optimization, but you have to make it really large to make it obvious, e.g. 1000 and so. this is because the WD gets multiplied by the LR, which is quite small, e.g. 1e-4, so the effect is small to notice.
- when you do notice it, the effect is the same for both versions, supporting correctness.
> add weight decay

- train_gpt2.cu
should fix ZeRO-1, if I got the logic for the selected subsections right.
training loss matches at least for the first three steps.
> run Adam only for parameters that are available on the local device

- train_gpt2.py
`torchrun --nproc-per-node=8 --nnodes=1 train_gpt2.py --model gpt2-xl --dtype bfloat16 --input_bin dev/data/tinyshakespeare/tiny_shakespeare_train.bin --compile 1 --flash 1 --tensorcores 1 --write_tensors 0 --num_iterations 50 --batch_size 2 --sequence_length 1024 --total_batch_size 524288 --zero_stage 0`
consumes 44.6GB at `(5267.100 ms, 99540 tok/s)` in A100s.
`--zero_stage 1` uses 33.8GB at `(5126.690 ms, 102266 tok/s)`
> Optional Zero1 changes for pytorch training

- dev/unistd.h
Adds support for the dirent.h functions in dev/unistd.h.
Please make sure and #ifndef _WIN32 around the use of <dirent.h>.
> Adding dirent.h support to unistd.h

- dataloader.h
- rand.h
- train_gpt2.cu
writes the files but doesn't load them yet, coming up in a bit
> resume training v1

- .github/workflows/ci.yml
Adds manual trigger functionality for our CI
> Adding manual trigger for CI

- dev/cuda/README.md
Minor fix noticed a discrepancy between the Make file and README.
> Update compile cmd in the dev/cuda README

- llmc/rand.h
Nit: add some clarification for folks not familiar with Box-Muller. There is a nice mention of it in the Mathematics for ML book (Deisenroth et al).
> Add clarification on Box-Muller

- train_gpt2.cu
extrapolating from spec sheets, yay :)
> MFU for other GPUs

- dev/vislog.ipynb
- llmc/logger.h
- train_gpt2.cu
Other than loss, gradient norm and learning rate tell a lot of information about the training dynamics:
1) modified the logger to support logging these 2 quantities
2) updated jupyter notebook parser
> Improve logger, add grad norm + learning rate

- train_gpt2.cu
Instead of looking for a dot check whether the path:
1) does not exist
2) or is a file instead of a dir
Hit this one trying to save to our llm.c directory :) so dot in the name is not really a good heuristic for us :P
> Minor fix - better handling of out log dir

- .github/workflows/ci_gpu.yml
@karpathy - will need you to hook up your repo (if you haven't already). This should fail since it will try to get a GPU runner that your repo does not have access to (yet). Once the GPU runner is hooked up - you can re-run this workflow to see if it passes.
Thanks to Ubicloud and Nvidia for the help and for sponsoring this.
> Adding GPU CI workflow file

- test_gpt2.cu
- train_gpt2.cu
Towards having our CI actually _test_ our code.
@rosslwheeler I just added the commands to run, I guess there is some more config needed to ensure this runs on GPU runners
> Testability

- README.md
For folks new to the C world this tip can be helpful.
> Add a debugging tip to README

- llmc/adamw.cuh
- llmc/cuda_utils.cuh
- llmc/global_norm.cuh
- llmc/zero.cuh
- profile_gpt2.cu
- profile_gpt2cu.py
- test_gpt2.cu
- train_gpt2.cu
An updated version of #361 
Things get a bit annoying, with the shards no longer being a single contiguous memory region, but instead each tensor ending  up sharded individually.
Some of our Adam/Norm calls will be super tiny due to that, so there should be some follow-on optimization, or, probably even better, some reorganization of the data layout.
> Overlap computation and communication V2

- dev/cuda/classifier_fused.cu
- dev/cuda/common.h
- dev/cuda/global_norm.cu
- dev/cuda/layernorm_backward.cu
- dev/cuda/layernorm_forward.cu
Add the faster kernels we use in "prod" to our "dev" kernels.
> Add global norm prod kernels to dev

- .github/workflows/ci_gpu.yml
- dev/cuda/adamw.cu
- dev/cuda/classifier_fused.cu
- dev/cuda/crossentropy_softmax_backward.cu
- llmc/gelu.cuh
- llmc/layernorm.cuh
Minor refactor + made sure that the lack of guards in `residual_forward`, `gelu_forward`, and `gelu_backward_inplace` is justified.
> Fix guarding logic, refactor

- README.md
Realized we didn't have this in the README so had to skim through our Discord history.
> Add NCCL instruction to README

- profile_gpt2.cu
- test_gpt2.cu
- train_gpt2.cu
Our backward step does all reduce as well now.
> Minor refactor

- dev/data/fineweb.py
Adding edu-fineweb support https://huggingface.co/datasets/HuggingFaceFW/fineweb-edu
How to use it : 
for 10B : `python fineweb.py -t "edu" -v "10B"`
for 100B : `python fineweb.py -t "edu" -v "100B"`
And in the launching script: 
```
-i "dev/data/fineweb10B/edu_fineweb_train_*.bin" \
-j "dev/data/fineweb10B/edu_fineweb_val_*.bin" \
```
> add edu fineweb support, with 10B and 100B version

- profile_gpt2.cu
- test_gpt2.cu
- train_gpt2.cu
removed the zero-grad utility; integrated gradient-zeroing fully into backward, removing the unnecessary sync point
> zero-grad is async and part of backward call

- dev/unistd.h
- llmc/cudnn_att.cpp
- llmc/utils.h
- This resolves issue https://github.com/karpathy/llm.c/issues/642
- Add small change to move WIN32 code from utils.h into unistd.h
> Fix for upgraded Cuda 12.5.1 and Microsoft latest compiler

- dev/cuda/attention_backward.cu
- dev/cuda/attention_forward.cu
- dev/cuda/classifier_fused.cu
- dev/cuda/nccl_all_reduce.cu
- dev/cuda/trimat_forward.cu
Minimal PR to fix a few memory leaks in dev cuda kernels.
> fix(dev/cuda): memory leaks

- Makefile
- llmc/mfu.h
- train_gpt2.cu
Prints additional GPU statistics such as power draw and temperature, fan speed and utilization (how much the GPU was busy; does not take into account if the GPU was busy in a useful way)
> Nvidia management library for more detailed GPU state printing

- README.md
This is a fork of llm.c,  featuring a single-header [tinytorch.hpp](https://github.com/GaoYusong/llm.cpp/blob/main/tinytorch.hpp) library. This library implements autograd and contains all the operators needed to support training the GPT-2 model. After studying your “Neural Networks: Zero to Hero” series, I created this project. It’s my first deep learning project, and I’m incredibly grateful for your intuitive and hands-on teaching.
At present, it only supports CPU. I hope CUDA support can be added in the future.
> add llm.cpp(a port of this project featuring a tinytorch.hpp library) link to notable forks in readme

- llmc/layernorm.cuh
> Fused rmsnorm reference
